# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_content',
            new_name='feedback_content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_time',
            new_name='feedback_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feed_contact',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
