# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170601_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date2',
            field=models.CharField(default='2017-06-01 01:58:27', max_length=50),
        ),
    ]
