# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20170601_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date2',
        ),
        migrations.AlterField(
            model_name='reg_vip',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
